name: app
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - astor=0.8.0
  - astroid=2.4.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - c-ares=1.15.0
  - ca-certificates=2020.4.5.2
  - certifi=2020.4.5.2
  - cython=0.29.17
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - gast=0.3.3
  - gmp=6.1.2
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.4
  - importlib-metadata=1.6.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.17.0
  - jinja2=2.11.2
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - keras=2.1.6
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.12.3
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mock=4.0.2
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - notebook=6.0.3
  - openssl=1.1.1g
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - protobuf=3.12.3
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pylint=2.5.2
  - pyrsistent=0.16.0
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - readline=8.0
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=47.1.1
  - six=1.15.0
  - sqlite=3.31.1
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - click==7.1.2
    - cycler==0.10.0
    - dataclasses==0.7
    - fastapi==0.58.0
    - h11==0.9.0
    - httptools==0.1.1
    - imageio==2.8.0
    - imgaug==0.4.0
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - networkx==2.4
    - numpy==1.14.1
    - opencv-python==4.2.0.34
    - pillow==7.1.2
    - pydantic==1.5.1
    - pyparsing==2.4.7
    - python-dotenv==0.13.0
    - python-multipart==0.0.5
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - shapely==1.7.0
    - starlette==0.13.4
    - tifffile==2020.6.3
    - uvicorn==0.11.5
    - uvloop==0.14.0
    - websockets==8.1

