name: updated-app
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - keras=2.1.6
  - numpy=1.14.1
  - python=3.6.10

  - pip:
    - fastapi
    - imgaug
    - scikit_image==0.13.1
    - uvicorn
 

